# Generated by Django 4.2.7 on 2025-12-27 16:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(default='India', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('bounds', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='City boundary polygon', null=True, srid=4326)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional city metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('parameters', models.JSONField(default=dict, help_text='Scenario parameters (e.g., vegetation_change, building_density)')),
                ('time_horizon', models.CharField(choices=[('1d', '1 Day'), ('7d', '7 Days'), ('30d', '30 Days'), ('1y', '1 Year'), ('5y', '5 Years'), ('10y', '10 Years')], default='1y', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='core.city')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Traffic measurement location', null=True, srid=4326)),
                ('volume', models.IntegerField(blank=True, help_text='Traffic volume (vehicles/hour)', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Average speed in km/h', null=True)),
                ('congestion_level', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('severe', 'Severe')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional traffic metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_data', to='core.city')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['city', 'timestamp'], name='core_traffi_city_id_c9682f_idx'), models.Index(fields=['timestamp'], name='core_traffi_timesta_e67b92_idx')],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('weather', 'Weather (GraphCast)'), ('climate', 'Climate (ClimaX)'), ('traffic', 'Traffic'), ('pollution', 'Pollution')], max_length=20)),
                ('timestamp', models.DateTimeField(help_text='Timestamp for which prediction is made')),
                ('predictions', models.JSONField(help_text='Prediction results (format depends on model_type)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.scenario')),
            ],
            options={
                'ordering': ['-timestamp', '-created_at'],
                'indexes': [models.Index(fields=['scenario', 'model_type'], name='core_predic_scenari_81b512_idx'), models.Index(fields=['timestamp'], name='core_predic_timesta_015d88_idx')],
            },
        ),
        migrations.CreateModel(
            name='PollutionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Pollution measurement location', null=True, srid=4326)),
                ('aqi', models.IntegerField(blank=True, help_text='Air Quality Index', null=True)),
                ('pm25', models.FloatField(blank=True, help_text='PM2.5 concentration in µg/m³', null=True)),
                ('pm10', models.FloatField(blank=True, help_text='PM10 concentration in µg/m³', null=True)),
                ('no2', models.FloatField(blank=True, help_text='NO2 concentration in µg/m³', null=True)),
                ('so2', models.FloatField(blank=True, help_text='SO2 concentration in µg/m³', null=True)),
                ('co', models.FloatField(blank=True, help_text='CO concentration in mg/m³', null=True)),
                ('o3', models.FloatField(blank=True, help_text='O3 concentration in µg/m³', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional pollution metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollution_data', to='core.city')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['city', 'timestamp'], name='core_pollut_city_id_f51e26_idx'), models.Index(fields=['timestamp'], name='core_pollut_timesta_4f231e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('humidity', models.FloatField(blank=True, help_text='Humidity percentage', null=True)),
                ('precipitation', models.FloatField(blank=True, help_text='Precipitation in mm', null=True)),
                ('wind_speed', models.FloatField(blank=True, help_text='Wind speed in m/s', null=True)),
                ('wind_direction', models.FloatField(blank=True, help_text='Wind direction in degrees', null=True)),
                ('pressure', models.FloatField(blank=True, help_text='Atmospheric pressure in hPa', null=True)),
                ('solar_radiation', models.FloatField(blank=True, help_text='Solar radiation in W/m²', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional climate metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_data', to='core.city')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['city', 'timestamp'], name='core_climat_city_id_f2f28f_idx'), models.Index(fields=['timestamp'], name='core_climat_timesta_50f242_idx')],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(help_text='OpenStreetMap ID', unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='Building footprint geometry', srid=4326)),
                ('building_type', models.CharField(blank=True, help_text='Type of building (residential, commercial, etc.)', max_length=100)),
                ('height', models.FloatField(blank=True, help_text='Building height in meters', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional building metadata from OSM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='core.city')),
            ],
            options={
                'ordering': ['osm_id'],
                'indexes': [models.Index(fields=['city', 'building_type'], name='core_buildi_city_id_57586f_idx'), models.Index(fields=['osm_id'], name='core_buildi_osm_id_e414af_idx')],
            },
        ),
    ]
